### ISSUE TITLE
Is there a simple\short installation tutorial?

### ISSUE THREAD

**Issue by NowLoadY** [ic1414/esp_quad#4]
I'm not very familiar with your project, but I think it interesting. Are there any related video or articles?  
And thanks for working on your project, it's nice!

**Comment by ic1414** [comment]
Sorry @NowLoadY, there is no short installation tutorial in English yet, but in Chinese. English version will be available soon(within one month).

**Comment by ic1414** [comment]
@NowLoadY. you can find tutorial in English here https://github.com/ic1414/esp_quad/tree/main/document/esp_quad_tutorial_v1 .

**Comment by NowLoadY** [comment]
> @NowLoadY. you can find tutorial in English here https://github.com/ic1414/esp_quad/tree/main/document/esp_quad_tutorial_v1 . 

thanks！！！🙏
